/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package abd.p1.view;

import abd.p1.controller.UserController;
import abd.p1.controller.UsuarioObserver;
import abd.p1.model.Busca;
import abd.p1.model.Genero;
import abd.p1.model.Usuario;
import com.toedter.calendar.JCalendar;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;

/**
 *
 * @author slide22
 */
public class EditUserDialog extends javax.swing.JDialog implements UsuarioObserver {

    private UserController controller;

    /**
     * Creates new form EditUser
     *
     * @param controller
     * @param parent
     * @param modal
     */
    public EditUserDialog(UserController controller, java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.controller = controller;

        Usuario user = controller.getUser();

        if (user.getAvatar() != null) {
            this.avatarPanel.setIcon(new ImageIcon(user.getAvatar()));
        }

        this.nombreLabel.setText(user.getNombre());

        if (user.getFechaDeNacimiento() != null) {
            Calendar cal = new GregorianCalendar();
            cal.setTime(user.getFechaDeNacimiento());
            this.edadLabel.setText(Integer.toString(calcularEdad(cal)) + " años");
        }

        this.descripcionArea.setText(user.getDescripcion());

        DefaultListModel modelo = new DefaultListModel();
        for (String aficion : user.getAficiones()) {
            modelo.addElement(aficion);
        }
        aficionesList.setModel(modelo);

        this.sexoLabel.setText("Sexo: " + user.getSexo());

        this.buscaLabel.setText("Busca: " + user.getBusca());
    }

    private EditUserDialog(JFrame jFrame, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        avatarPanel = new abd.p1.view.AvatarPanel();
        nombreLabel = new javax.swing.JLabel();
        edadLabel = new javax.swing.JLabel();
        changeNombreBtn = new javax.swing.JButton();
        fechaNacimientoBtn = new javax.swing.JButton();
        avatarBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        descripcionArea = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        aficionesList = new javax.swing.JList<>();
        addAficionBtn = new javax.swing.JButton();
        delAficionBtn = new javax.swing.JButton();
        editAficionBtn = new javax.swing.JButton();
        sexoBtn = new javax.swing.JButton();
        preferenciaBtn = new javax.swing.JButton();
        sexoLabel = new javax.swing.JLabel();
        buscaLabel = new javax.swing.JLabel();
        passBtn = new javax.swing.JButton();
        candelBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout avatarPanelLayout = new javax.swing.GroupLayout(avatarPanel);
        avatarPanel.setLayout(avatarPanelLayout);
        avatarPanelLayout.setHorizontalGroup(
            avatarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );
        avatarPanelLayout.setVerticalGroup(
            avatarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        nombreLabel.setText("Nombre");

        edadLabel.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        edadLabel.setText("Edad");

        changeNombreBtn.setText("Cambiar nombre");
        changeNombreBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeNombreBtnActionPerformed(evt);
            }
        });

        fechaNacimientoBtn.setText("Cambiar fecha de nacimiento");
        fechaNacimientoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaNacimientoBtnActionPerformed(evt);
            }
        });

        avatarBtn.setText("Cambiar avatar");
        avatarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avatarBtnActionPerformed(evt);
            }
        });

        descripcionArea.setColumns(20);
        descripcionArea.setRows(5);
        jScrollPane1.setViewportView(descripcionArea);

        jLabel4.setText("Descripción");

        jLabel5.setText("Aficiones");

        jScrollPane2.setViewportView(aficionesList);

        addAficionBtn.setLabel("Añadir afición");
        addAficionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAficionBtnActionPerformed(evt);
            }
        });

        delAficionBtn.setLabel("Eliminar seleccionada");
        delAficionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delAficionBtnActionPerformed(evt);
            }
        });

        editAficionBtn.setLabel("Editar seleccionada");
        editAficionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editAficionBtnActionPerformed(evt);
            }
        });

        sexoBtn.setLabel("Cambiar sexo");
        sexoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexoBtnActionPerformed(evt);
            }
        });

        preferenciaBtn.setText("Cambiar preferencia");
        preferenciaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preferenciaBtnActionPerformed(evt);
            }
        });

        sexoLabel.setText("Sexo:");

        buscaLabel.setText("Busca:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(avatarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombreLabel)
                                    .addComponent(edadLabel)))
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(avatarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(changeNombreBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fechaNacimientoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sexoLabel)
                                    .addComponent(buscaLabel))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(preferenciaBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sexoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(addAficionBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(delAficionBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(editAficionBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreLabel)
                            .addComponent(changeNombreBtn))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edadLabel))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fechaNacimientoBtn))))
                    .addComponent(avatarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(avatarBtn)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(addAficionBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delAficionBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editAficionBtn))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sexoBtn)
                    .addComponent(sexoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(preferenciaBtn)
                    .addComponent(buscaLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        passBtn.setText("Cambiar contraseña");
        passBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passBtnActionPerformed(evt);
            }
        });

        candelBtn.setText("Cancelar");
        candelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                candelBtnActionPerformed(evt);
            }
        });

        saveBtn.setText("Guardar cambios");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(passBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(candelBtn)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passBtn)
                    .addComponent(candelBtn)
                    .addComponent(saveBtn))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changeNombreBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeNombreBtnActionPerformed
        String nuevoNombre = JOptionPane.showInputDialog(this, "Introduce tu nombre", this.controller.getUser().getNombre());
        if (!nuevoNombre.isEmpty()) {
            this.controller.changeNombre(nuevoNombre);
        }
    }//GEN-LAST:event_changeNombreBtnActionPerformed

    private void fechaNacimientoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaNacimientoBtnActionPerformed
        JCalendar cal = new JCalendar();
        cal.setDate(this.controller.getUser().getFechaDeNacimiento());
        String message = "Elige tu fecha de nacimiento:\n";
        Object[] params = {message, cal};
        if (JOptionPane.showConfirmDialog(this, params, "Fecha de nacimiento", JOptionPane.PLAIN_MESSAGE) == JOptionPane.OK_OPTION) {
            this.controller.changeFechaNacimiento(cal.getDate());
        }
    }//GEN-LAST:event_fechaNacimientoBtnActionPerformed

    private void avatarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avatarBtnActionPerformed
        JFileChooser files = new JFileChooser();
        int result = files.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {

            try {
                FileInputStream input = new FileInputStream(files.getSelectedFile());
                byte[] data = new byte[input.available()];
                input.read(data);
                input.close();
                this.controller.changeAvatar(data);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Error al cargar el avatar", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_avatarBtnActionPerformed

    private void addAficionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAficionBtnActionPerformed
        String aficion = JOptionPane.showInputDialog(this, "Introduce una afición");
        if (aficion != null) {
            this.controller.addAficion(aficion);
        }
    }//GEN-LAST:event_addAficionBtnActionPerformed

    private void delAficionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delAficionBtnActionPerformed
        String aficion = this.aficionesList.getSelectedValue();
        this.controller.delAficion(aficion);
    }//GEN-LAST:event_delAficionBtnActionPerformed

    private void editAficionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editAficionBtnActionPerformed
        String aficion = this.aficionesList.getSelectedValue();
        String nuevaAficion = JOptionPane.showInputDialog(this, "Editar afición", aficion);
        if (nuevaAficion != null) {
            this.controller.editAficion(aficion, nuevaAficion);
        }
    }//GEN-LAST:event_editAficionBtnActionPerformed

    private void sexoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexoBtnActionPerformed
        Genero[] gen = {Genero.MASCULINO, Genero.FEMENINO};
        JComboBox<Genero> sexoCombo = new JComboBox<>(gen);

        String message = "Elige tu sexo:\n";
        Object[] params = {message, sexoCombo};
        if (JOptionPane.showConfirmDialog(this, params, "Elige tu sexo", JOptionPane.PLAIN_MESSAGE) == JOptionPane.OK_OPTION) {
            this.controller.changeSexo((Genero) sexoCombo.getSelectedItem());
        }
    }//GEN-LAST:event_sexoBtnActionPerformed

    private void preferenciaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preferenciaBtnActionPerformed
        Busca[] busca = {Busca.HOMBRES, Busca.MUJERES, Busca.AMBOS};
        JComboBox<Busca> buscaCombo = new JComboBox<>(busca);

        String message = "Elige tu preferencia:\n";
        Object[] params = {message, buscaCombo};
        if (JOptionPane.showConfirmDialog(this, params, "Elige tu preferencia", JOptionPane.PLAIN_MESSAGE) == JOptionPane.OK_OPTION) {
            this.controller.changePreferencia((Busca) buscaCombo.getSelectedItem());
        }
    }//GEN-LAST:event_preferenciaBtnActionPerformed

    private void passBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passBtnActionPerformed
        JLabel l1 = new JLabel("Contraseña");
        JPasswordField pass1 = new JPasswordField();
        JLabel l2 = new JLabel("Repite la contraseña");
        JPasswordField pass2 = new JPasswordField();

        Object[] params = {l1, pass1, l2, pass2};
        if (JOptionPane.showConfirmDialog(this, params, "Cambiar contraseña", JOptionPane.PLAIN_MESSAGE) == JOptionPane.OK_OPTION) {

            if (String.valueOf(pass1.getPassword()).equals(String.valueOf(pass2.getPassword()))) {
                this.controller.changePassword(String.valueOf(pass1.getPassword()));
            } else {
                JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_passBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        this.controller.changeDescripcion(descripcionArea.getText());
        this.controller.saveChanges();
        this.dispose();
    }//GEN-LAST:event_saveBtnActionPerformed

    private void candelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_candelBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_candelBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditUserDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditUserDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditUserDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditUserDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            EditUserDialog dialog = new EditUserDialog(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAficionBtn;
    private javax.swing.JList<String> aficionesList;
    private javax.swing.JButton avatarBtn;
    private abd.p1.view.AvatarPanel avatarPanel;
    private javax.swing.JLabel buscaLabel;
    private javax.swing.JButton candelBtn;
    private javax.swing.JButton changeNombreBtn;
    private javax.swing.JButton delAficionBtn;
    private javax.swing.JTextArea descripcionArea;
    private javax.swing.JLabel edadLabel;
    private javax.swing.JButton editAficionBtn;
    private javax.swing.JButton fechaNacimientoBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JButton passBtn;
    private javax.swing.JButton preferenciaBtn;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton sexoBtn;
    private javax.swing.JLabel sexoLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onNombreChange(String nombre) {
        this.nombreLabel.setText(nombre);
    }

    @Override
    public void onFechaDeNacimientoChange(Date fecha) {
        Calendar cal = new GregorianCalendar();
        cal.setTime(fecha);

        this.edadLabel.setText(Integer.toString(calcularEdad(cal)) + " años");
    }

    private int calcularEdad(Calendar fechaNac) {

        Calendar today = Calendar.getInstance();
        int diffYear = today.get(Calendar.YEAR) - fechaNac.get(Calendar.YEAR);
        int diffMonth = today.get(Calendar.MONTH) - fechaNac.get(Calendar.MONTH);
        int diffDay = today.get(Calendar.DAY_OF_MONTH) - fechaNac.get(Calendar.DAY_OF_MONTH);
        // Si está en ese año pero todavía no los ha cumplido
        if (diffMonth < 0 || (diffMonth == 0 && diffDay < 0)) {
            diffYear = diffYear - 1; // no aparecían los dos guiones del
        }

        return diffYear;

    }

    @Override
    public void onAvatarChange(byte[] avatar) {
        this.avatarPanel.setIcon(new ImageIcon(avatar));
    }

    @Override
    public void onAficionesChange(List<String> aficiones) {
        DefaultListModel modelo = new DefaultListModel();
        modelo.clear();

        aficiones.stream().forEach((aficion) -> {
            modelo.addElement(aficion);
        });

        aficionesList.setModel(modelo);
    }

    @Override
    public void onSexoChange(Genero sexo) {
        this.sexoLabel.setText("Sexo: " + sexo);
    }

    @Override
    public void onPreferenciaChange(Busca busca) {
        this.buscaLabel.setText("Busca: " + busca);
    }

    @Override
    public void onPassChange(String pass) {
        JOptionPane.showMessageDialog(this, "Contraseña cambiada correctamente");
    }
}
